global:
  scrape_interval: 15s

scrape_configs:
  - job_name: payment
    static_configs:
      - targets:
          - payment:3001
  - job_name: consumer-app
    static_configs:
      - targets:
          - consumer-app:3002
  - job_name: driver-app
    static_configs:
      - targets:
          - driver-app:3003
  - job_name: booking-service
    static_configs:
      - targets:
          - booking-service:3004
