name: Deploy to UAT

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-uat'

permissions:
  contents: write
  security-events: write

jobs:
  # 1. Booking Service
  deploy-booking-service:
    uses: ./.github/workflows/reusable-ci-cd.yml
    with:
      service-name: booking-service
      environment: uat
      image-name: booking-service

  # 2. Payment Service
  deploy-payment-service:
    uses: ./.github/workflows/reusable-ci-cd.yml
    with:
      service-name: payment
      environment: uat
      image-name: payment

  # 3. Driver App
  deploy-driver-app:
    uses: ./.github/workflows/reusable-ci-cd.yml
    with:
      service-name: driver-app
      environment: uat
      image-name: driver-app

  # 4. Consumer App
  deploy-consumer-app:
    uses: ./.github/workflows/reusable-ci-cd.yml
    with:
      service-name: consumer-app
      environment: uat
      image-name: consumer-app

