name: Prod

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag to promote"
        required: true
        type: string

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-ci-cd.yml
    with:
      environment: prod
      image_tag: ${{ inputs.image_tag }}
      deploy: true
    secrets: inherit
